package dev.revere.alley.base.arena.artificial;

import dev.revere.alley.base.arena.AbstractArena;
import dev.revere.alley.base.arena.enums.EnumArenaType;
import dev.revere.alley.core.lifecycle.IService;
import org.bukkit.entity.Player;

import java.util.concurrent.CompletableFuture;

/**
 * @author Remi
 * @project alley-practice
 * @date 6/07/2025
 */
public interface IArenaBuildService extends IService {
    /**
     * Executes a JSON build script to create a new arena.
     * This is an asynchronous operation that provides feedback to the issuer.
     *
     * @param issuer The player who initiated the build.
     * @param arenaName The name for the new arena.
     * @param arenaType The type of arena (SHARED or STANDALONE).
     * @param jsonScript The build script generated by the AI.
     * @return A CompletableFuture that completes when the build is finished.
     */
    CompletableFuture<AbstractArena> buildArenaFromScript(Player issuer, String arenaName, EnumArenaType arenaType, String jsonScript);
}